services:
  server:
    build:
      context: ./ProductUpdatesServer
      dockerfile: Dockerfile
    container_name: signalr-server
    ports:
      - "5170:5170"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5170
    networks:
      - signalr-network

  client:
    build:
      context: ./product-updates-client
      dockerfile: Dockerfile
    container_name: signalr-client
    ports:
      - "4200:80"
    depends_on:
      - server
    networks:
      - signalr-network

networks:
  signalr-network:
    driver: bridge
